ipxe.go
Previously an error listening and serving would not cause the private listen and serve functions of `ipxe.go` to return an error until the context was canceled. This allows the error to propagate immediately.
Fixes: #
I have:
=> Fix error not returning immediately:

ipxe.go, ipxe_test.go
If users do not want/need a service, it can be disabled.
This is helpful, for example, when TFTP is not needed/desired.
https://github.com/tinkerbell/boots/pull/229#discussion_r772673218
Fixes: #
I have:
=> Add ability to disable TFTP and HTTP:

README.md, binary/script/build_and_pr.sh, cmd.go, cmd/main.go, cmd_test.go, docs/Philosophy.md, example/main.go, go.mod, ihttp/ihttp.go, ihttp/ihttp_test.go, ipxedust.go, ipxedust_test.go, itftp/itftp.go, itftp/itftp_test.go, lint.mk
The current user experience for importing `tinkerbell/boots-ipxe` is that the import must be renamed.
```Go
import (
ipxe "github.com/tinkerbell/boots-ipxe"
)
func main() {
srv := ipxe.Server{}
srv.ListenAndServer(ctx)
}
```
The guidance from the Go maintainers is that "good package names should not require renaming." --[ref](https://github.com/golang/go/wiki/CodeReviewComments#imports)
This change will make importing look like this:
```Go
import (
"github.com/tinkerbell/ipxedust"
)
func main() {
ipxe := ipxedust.Server{}
ipxe.ListenAndServer(ctx)
}
```
Fixes: #18 
I have:
=> Rename repo from boots-ipxe to ipxedust:

cmd.go, cmd_test.go, ipxedust.go, ipxedust_test.go
A standard TFTP server implementation receives requests on port 69 and
allocates a new high port (over 1024) dedicated to that request.
In single-port mode, the same port is used for transmit and receive.
If the server is started on port 69, all communication will be done on port 69.
This option is required when running in a container, that doesn't bind to the hosts
network, because this type of dynamic port allocation is not generally supported.
Fixes: #
I have:
=> Add ability to enable single port mode for the TFTP server:

ihttp/ihttp.go, ihttp/ihttp_test.go, ipxedust.go
HTTPClient network boot clients use the HEAD method to get the size before downloading.
https://github.com/tinkerbell/boots/pull/216/files#diff-a8783392d81a537e4fb749c1b3e44b23ad376a7ee72440e0cefe1597ddd28acfR24-R27
https://github.com/tinkerbell/boots/pull/229#issuecomment-1011467759
Fixes: #
I have:
=> Head method

binary/script/ipxe-customizations/common.h
This PR allows devices to poweroff during the IPXE stage.  
In Equinix Metal settings, this allows for scheduled customizations, say to userdata, based on device details that can not be known until the on-demand device is selected and provisioned.
In Tinkerbell settings, this allows for IPXE scripts to perform tasks and then conserve power until awoken by the BMC or user.
Adding this capability should be harmless since the capability is already present at later (and depending on the environment, earlier) stages.
Devices have the capability to poweroff at anytime from an IPXE chained boot. Devices can even reboot from within IPXE with the options provided today.
Related request: https://feedback.equinixmetal.com/operating-systems/p/enable-the-poweroff-command-in-the-ipxe-image
I have:
=> include the POWEROFF_CMD in ipxe builds

binary/script/ipxe-customizations/common.h
Enable the built in ping command inside of the iPXE environment.
Port of tinkerbell/boots#181
Operators debugging network issues sometimes find it useful to be able to issue ping commands from the iPXE environment to verify network configuration.
If this was intentionally not brought over from boots, feel free to close this without merging.
This has not been tested yet. Do we want to bring over some of the testing that I implemented for the ipxe build in boots?
=> Enable the iPXE ping command

binary/script/build_and_pr.sh, binary/script/build_ipxe.sh, binary/script/ipxe-customizations/crypto.h
disabling ocsp_check to match original tinkerbell/boots configuration
https://github.com/tinkerbell/boots/blob/bd87a7a7a95d25077f183c298c003335fc67e031/ipxe/ipxe/build.sh#L14
This is also disabled in other widely used ipxe builds such as
netboot.xyz
https://github.com/netbootxyz/netboot.xyz/blob/d8a5c3e8e88772ea3d74175faa012cf575afe707/roles/netbootxyz/files/ipxe/local/crypto.h
With this enabled, ipxe has issues validating tls within a private
environment that has no route to the internet to do ocsp checks.
Fixes: #
I have:
=> disable ocsp check

cmd.go
The cli flag wasn't being honored.
Fixes: #
I have:
=> Plumb cli flag for tftp-single-port through to config:

.github/workflows/ipxe.yaml, Makefile, binary/script/build_ipxe.sh, binary/script/fetch_and_extract_ipxe.sh, binary/script/shell.nix
Fixes to Makefile/build system so parallel builds work better.
Parallel builds were previously racy and/or wasting time and bandwidth. We could have either been fetching ipxe source files multiple times (potentially once for each target) or the first build_ipxe.sh to run will start to fetch the tarball and subsequent ones could see the incomplete file and begin to try and extract it with all sorts of fun ensuing.
I've forced fetching/rebuilding of the ipxe files multiple times with no problems. I've also interrupted both curl and tar and verified that next invocations do the right thing.
More reliable builds.
I have:
=> Make it correctly

binary/script/embed.ipxe
This allows creating an interface with a vlan tag based off of DHCP option 43, suboption 116. This will not change the existing behavior. The vlan interface is only created if DHCP option 43.116 is set. This PR is the start of the implementation of [proposal 28](https://github.com/tinkerbell/proposals/pull/60).
Fixes: #
I have manually test this.
No impact.
I have:
=> Add vlan support to embedded script:

binary/script/ipxe-customizations/common.h
Enable the iPXE certificate management commands
See https://ipxe.org/buildcfg/cert_cmd
Enables
- [certstat](https://ipxe.org/cmd/certstat) 
- [certstore](https://ipxe.org/cmd/certstore)
- [certfree](https://ipxe.org/cmd/certfree)
Enables use of commands to debug TLS certificate issues.
I did local builds and used the resulting binaries.
Consumers of ipxedust need to update to the latest version after fresh binaries are built and merged.
I have:
=> Enable the iPXE certificate commands

ihttp/ihttp.go, ihttp/ihttp_test.go
This PR switches the HTTP server implementation to use http.ServeContent, which means that it now has support for more features like sending MIME types and handling range requests.
In certain cases, BMCs try to make HTTP range requests to avoid accessing downloading the entire boot media at once. With this change, those attempts no longer fail.
Booted a Dell R640 with a virtual media image hosted on ipxedust.
Should be no impact. HTTP server just supports more features.
I have:
=> Use http.ServeContent

binary/script/embed.ipxe
Adds a target for binary patching to the embedded ipxe script.
This splits off the script changes from #63. It is needed because that PR adds tests which will only pass once new binaries are generated incorporating the updated scripts.
N/A
N/A
I have:
=> Add binary patch target to ipxe script

binary/binary.go, binary/binary_test.go, ihttp/ihttp.go, ihttp/ihttp_test.go, ipxedust.go, itftp/itftp.go, itftp/itftp_test.go
This PR enables modifying the embedded ipxe script within served binaries at runtime.
It may seem very brittle to assume that the raw bytes of the script will directly end up in the final binary, but in practice this seems to work quite well and is vastly simpler than trying to unpack and repack the binaries.
This enables flexibility if the default boot script does not match user requirements, or if users want to pass additional information that will not be known at runtime.
We use this to add `dhcp && chain http://<ip-address>/auto.ipxe || shell` to the start of the script which prevents ipxe from having to query the network to find where it should chain boot from.
I confirmed that I was able to boot a machine with an ipxe script that had been patched using this method.
Default behavior …
=> Add support for patching embedded ipxe scripts

Makefile, binary/script/build_and_pr.sh, binary/script/build_ipxe.sh
Updates the build scripts to also produce an amd64 ipxe.iso binary. Once the CI has generated the binary, I'll make a follow-up PR to expose it from the ipxedust server.
An ISO file is another useful file format for booting servers. In particular, it is required to boot using a virtual cdrom drive.
Used the scripts to build an ISO and then booted a Dell server using it.
Adds about 2 MB to ipxedust.
I have:
=> Build ipxe.iso binary

binary/script/shell.nix
The build will fail without this. `util/genfsimg: could not find isolinux.bin`
Fixes: #
I have:
=> Add xorriso dependency for ipxe.iso build:

Makefile, binary/script/fetch_and_extract_ipxe.sh, binary/script/iso.patch, binary/script/shell.nix
The iPXE src build scripts for building `ipxe.iso` are hardcoded to look for the `isolinux.bin` in `/usr/lib/ISOLINUX`. This fixes the fixes iPXE iso build to work with our nix setup.
Fixes: #
I have:
=> Patch iPXE src to find isolinux.bin in the nix env:

binary/script/shell.nix
Fix the failing build for `ipxe.iso`.
Fixes: #
I have:
=> Add missing dependency for building ipxe.iso

binary/script/embed.ipxe
Modify the ipxe script to identify and autoboot from the interface that has successfully obtained an IP address through DHCP. Implementing this solution will result in a faster boot process and improved overall efficiency.
Fixes: #83
Fixes: #83
I have:
=> Autoboot from the interface that has obtained an IP address through DHCP

Makefile, binary/script/build_and_pr.sh, binary/script/shell.nix, docs/DifficultHardware.md
This PR adds code to build and ship a bootable floppy image (EFI only) that can boot straight into our EFI build of iPXE.
Operators dealing with finicky hardware may want to use this as described in `docs/DifficultHardware.md`
The resulting floppy image has been tested on some physical servers.
N/A
I have:
=> Build EFI bootable floppy ipxe.img

Makefile, binary/binary.go, binary/binary_test.go, binary/script/build_and_pr.sh, binary/script/build_ipxe.sh, example/main.go, ihttp/ihttp_test.go, itftp/itftp.go, lint.mk
Update iPXE build scripts. Instead of having the `build_ipxe.sh` handle running in docker or locally with nix, we remove all that out so that it is up to the user of `build_ipxe.sh` to get into a nix-shell using `binary/script/shell.nix`. The script no longer calls docker or nix to run the iPXE build. The purpose of this is to simplify the build process, adding features, maintainability, etc. This will also fix the build issue on main.
Also updated the `golangci-lint` to the latest version and resolve lint issues.
Fixes: #
I have:
=> iPXE build scripts update

Makefile, binary/script/shell.nix
Switch the boot floppy to use GPT partitioning
The GPT partition table allows us to label the partition more clearly
which makes it easier for other tooling to detect / ignore it.
Mostly just on my NixOS machine, though also under docker in #90 which is no longer needed thanks to #89
N/A
=> floppy: switch to gpt partitioning

cmd.go, cmd_test.go, ipxedust.go
This PR adds the ability to set a higher maximum block size for TFTP transfers.
We are troubleshooting some misbehaving NICs that might benefit from support for larger block sizes. They appear to request 1468 which makes sense on a link with MTU of 1500.
Tested with atftp
The default of 512 is preserved and made explicit in this codebase.
=> Add ability to set a higher maximum block size for TFTP

binary/script/build_and_pr.sh, binary/script/build_ipxe.sh, binary/script/ipxe-customizations/nap.h
- see https://github.com/ipxe/ipxe/discussions/605#discussioncomment-2273515
- "This will cause iPXE to leave the CPU spinning instead of putting it to sleep, and will avoid the problems on U-Boot."
- Seems harmless on non U-Boot machines -- the CPU will spin during the key timeout (2s?) but that's about it.
=> ipxedust: add nap.h to arm64 build to set NAP_NULL to support u-boot

binary/script/embed.ipxe
This resolves issues when an interface might need some time before the upstream port is forwarding properly or if the firmware is slow, etc. I found this to make a Raspberry PI 4b boot consistently. This was also tested and resolved consistency issues with Cisco ACI switches using LACP configured interfaces.
Fixes: #
I have:
=> Add dhcp retries to embedded iPXE script:

binary/script/build_ipxe.sh
This resolves an issue where large file downloads will hang on Broadcom NetXtreme NICs. This issue was caused by commit [`059c4dc`](https://github.com/ipxe/ipxe/commit/059c4dc688cea6d9398d63ca10f5c00e94ae2159) which changed how drivers are loaded by iPXE. [A fix](https://github.com/ipxe/ipxe/issues/1023#issuecomment-1898585257) was identified in [this issue](https://github.com/ipxe/ipxe/issues/1023) wherein the number of receive buffers (defined as `NUM_RX_BUFFERS` in `src/drivers/net/bnxt/bnxt.h`) is reduced from the default value of 8 to 2.
This is required to fix an issue where downloading large files (e.g. a kernel or initial RAM filesystem) will hang on Broadcom devices.
This change was tested by using the committed modifications, rebuilding the iPXE binaries[^1], and then rebuilding …
=> Reduce number of receive buffers to resolve download hangs on Broadcom NetXtreme NICs
